# Generated by Django 3.2.7 on 2023-07-09 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('first_alternative', models.TextField()),
                ('second_alternative', models.TextField()),
                ('third_alternative', models.TextField()),
                ('fourth_alternative', models.TextField()),
                ('fifth_alternative', models.TextField(blank=True)),
                ('answer', models.CharField(choices=[('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E', 5)], max_length=3)),
                ('is_answered', models.BooleanField(default=False)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercise')),
            ],
        ),
    ]
