# Generated by Django 3.2.7 on 2023-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='is_answered',
            field=models.BooleanField(default=True),
        ),
    ]
